### ISSUE TITLE
Linguagem MarkDown 📳

### ISSUE THREAD

**Issue by Venicio-Pinheiro** [Venicio-Pinheiro/ifpa20180793800TC795#1]
Estou aprendendo linguagem _MarkDown_ no **Curso em Video** de **Git e GitHub** do Professor *Gustavo Guanabara*.

# Aula de Linguagem Markdown
***
Podemos _*mistura*_ configurações

Lista Numerada
1. Lista 01
0. Lista 02
    1. Lista 04
999. lista 04 

Lista Demarcada
* Lista 01
* Lista 02
* Lista 03
   * Lista 3.1
* Lista 04

Lista de tarefas:

- [ ]  Criar a pagina principal
- [ ] Criar a pagina loja
- [ ] Finalizar a reunião com o cliente
- [ ] Receber pagamento

**Comment by Venicio-Pinheiro** [comment]
# Mascote do Github do Professor Gustavo Guanabara da plataforma _Curso em Video_.

![ mascote do github do professor Gustavo Guanabara ](https://user-images.githubusercontent.com/62081143/110647695-d09d9d80-8196-11eb-9be2-2361b31d71f1.png)


[Acesse meu Github]( https://github.com/Venicio-Pinheiro )

**Comment by Venicio-Pinheiro** [comment]
Num | Nome | Nota | Turno 
---|---|---|---
1 | Venicio | 9,0 | Noite
2 | Malu | 10 | Manhã
3 | Denise | 10 | Tarde
4 | Socorro | 10 | Tarde

**Comment by Venicio-Pinheiro** [comment]
Não entendo direito para que serve o comando `document.getElementById( )` da Linguagem JavaScript.


Olha meu Phyton
```
num = int(input('Digite um valor': ))
if num%2==0:
    print(f'O valor {num} é PAR')
else:
    print(f'O valor {num} é IMPAR')
```

**Comment by Venicio-Pinheiro** [comment]
Colocando emoji  🖖 👍 🐒

**Comment by wesleywpc** [comment]
#MarkDown
--
__Testando__ primeiro texto em **Markdown** da *minha* vida!

😝 Só nos printf()

**Comment by Venicio-Pinheiro** [comment]
Trabalho foi finalizado para testes.
